/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campeonato.GUI;

import campeonato.SRV.CampeonatoSRV;
import campeonato.SRV.EquipoSRV;
import campeonato.SRV.GrupoSRV;
import campeonato.SRV.JugadorSRV;
import campeonato.SRV.MODELOS.Equipo;
import campeonato.SRV.MODELOS.Grupo;
import campeonato.SRV.MODELOS.GrupoEquipo;
import campeonato.SRV.MODELOS.GrupoPK;
import campeonato.SRV.MODELOS.Jugador;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lara
 */
public class gestionCampeonatoGUI extends javax.swing.JDialog {

    /**
     * Creates new form gestionCampeonatoGUI
     */
    int idCampeonato = 13;
    public gestionCampeonatoGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCombosEquipos();
        idEquipoCB.setVisible(false);
        cargarEquipos();
        cargarJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        asignarEquiposBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gruposCB = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        equiposTBL = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        etapaCB = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        asignarJugadoresBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        equiposCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jugadoresTBL = new javax.swing.JTable();
        idEquipoCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Equipos - Jugadores");

        asignarEquiposBTN.setText("Asignar Equipos");
        asignarEquiposBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarEquiposBTNActionPerformed(evt);
            }
        });

        jLabel2.setText("Grupo");

        gruposCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        gruposCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gruposCBActionPerformed(evt);
            }
        });

        equiposTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nro", "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(equiposTBL);

        jLabel3.setText("Etapa");

        etapaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primera Ronda" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asignarEquiposBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etapaCB, 0, 170, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(gruposCB, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignarEquiposBTN)
                    .addComponent(jLabel2)
                    .addComponent(gruposCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(etapaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(416, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Asignar Equipos", jPanel1);

        asignarJugadoresBTN.setText("Asignar Jugadores");
        asignarJugadoresBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarJugadoresBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("Equipo");

        equiposCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiposCBActionPerformed(evt);
            }
        });

        jugadoresTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Cédula", "Nombres", "Apellidos", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jugadoresTBL);
        if (jugadoresTBL.getColumnModel().getColumnCount() > 0) {
            jugadoresTBL.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asignarJugadoresBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(idEquipoCB, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equiposCB, 0, 295, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignarJugadoresBTN)
                    .addComponent(jLabel1)
                    .addComponent(equiposCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idEquipoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(416, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(53, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Asignar Jugadores", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarDatos(int id){
        idCampeonato = id;
    }
    private void asignarJugadoresBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarJugadoresBTNActionPerformed
        // TODO add your handling code here:
        CampeonatoSRV campeonatoSRV = new CampeonatoSRV();
        try {
            campeonatoSRV.AsignarJugadores(11);
            JOptionPane.showMessageDialog(rootPane, "Jugadores asignados.", "Mensaje", JOptionPane.OK_OPTION);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.OK_OPTION);
        }

        
    }//GEN-LAST:event_asignarJugadoresBTNActionPerformed

    private void asignarEquiposBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarEquiposBTNActionPerformed
        // TODO add your handling code here:
        CampeonatoSRV campeonatoSRV = new CampeonatoSRV();
        try {
            campeonatoSRV.AgregarEquipos("Primera Ronda", 4, 4, idCampeonato);
            JOptionPane.showMessageDialog(rootPane, "Equipos asignados.", "Mensaje", JOptionPane.OK_OPTION);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_asignarEquiposBTNActionPerformed

    private void equiposCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiposCBActionPerformed
         // TODO add your handling code here:
         try{
             cargarJugadores();
         }catch(Exception e){
         }
    }//GEN-LAST:event_equiposCBActionPerformed

    private void gruposCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gruposCBActionPerformed
         // TODO add your handling code here:
         cargarEquipos();
    }//GEN-LAST:event_gruposCBActionPerformed
    
    public void cargarEquipos(){
        int idGrupo = 0;
        
        if(gruposCB.getSelectedItem() != null && etapaCB.getSelectedItem() != null){
            idGrupo = Integer.parseInt((String) gruposCB.getSelectedItem());
            GrupoPK gpk = new GrupoPK(idGrupo, (String) etapaCB.getSelectedItem(), idCampeonato);
            GrupoSRV grupoSRV = new GrupoSRV();
            Grupo grupo = grupoSRV.get(gpk);
            
            DefaultTableModel model = (DefaultTableModel) equiposTBL.getModel();
            //Borrar elementos anteriores
            for(int i = model.getRowCount() - 1; i >= 0 ; i--)
                model.removeRow(i);

            int n = 1;
            for(GrupoEquipo e : grupo.getGrupoEquipoCollection())
                model.addRow(new Object[]{n++, e.getEquipo().getIdEquipo(), e.getEquipo().getNombre()});

        }
        
    }
    
    public void cargarCombosEquipos(){
        EquipoSRV equipoSRV = new EquipoSRV();
        List<Equipo> equipos = equipoSRV.getAll();
        equiposCB.removeAllItems();
        idEquipoCB.removeAllItems();
        for(Equipo e : equipos){
            equiposCB.addItem(e.getNombre());
            idEquipoCB.addItem(e.getIdEquipo().toString());
        }
    }
    
    public void cargarJugadores(){
        
        int numero = equiposCB.getSelectedIndex();
        String id = idEquipoCB.getItemAt(numero);
        System.out.println(id);
        if(id != null){
            EquipoSRV equipoSRV = new EquipoSRV();
            int idEquipo = 0;
            idEquipo = Integer.parseInt(id);
            DefaultTableModel model = (DefaultTableModel) jugadoresTBL.getModel();
            //Borrar elementos anteriores
            for(int i = model.getRowCount() - 1; i >= 0 ; i--)
                model.removeRow(i);
            
            Equipo equipo = equipoSRV.get(idEquipo);
            int n = 1;
            for(Jugador j : equipo.getJugadorCollection())
                model.addRow(new Object[]{n++, j.getIdJugador(), j.getNombre(), j.getApellidos(), j.getTelefono()});

        }
        //int idEquipo = Integer.parseInt(idEquipoCB.getItemAt(numero));
        /*EquipoSRV equipoSRV = new EquipoSRV();
        int idEquipo = 0;
        idEquipo = Integer.parseInt(id);
        DefaultTableModel model = (DefaultTableModel) jugadoresTBL.getModel();
        //Borrar elementos anteriores
        for(int i = model.getRowCount() - 1; i >= 0 ; i--)
        model.removeRow(i);
        Equipo equipo = equipoSRV.get(idEquipo);
        int n = 1;
        for(Jugador j : equipo.getJugadorCollection())
        model.addRow(new Object[]{n++, j.getIdJugador(), j.getNombre(), j.getApellidos(), j.getTelefono()});
    */}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionCampeonatoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionCampeonatoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionCampeonatoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionCampeonatoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gestionCampeonatoGUI dialog = new gestionCampeonatoGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarEquiposBTN;
    private javax.swing.JButton asignarJugadoresBTN;
    private javax.swing.JComboBox<String> equiposCB;
    private javax.swing.JTable equiposTBL;
    private javax.swing.JComboBox<String> etapaCB;
    private javax.swing.JComboBox<String> gruposCB;
    private javax.swing.JComboBox<String> idEquipoCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jugadoresTBL;
    // End of variables declaration//GEN-END:variables
}
